image: weyforth/drone-docker
environment:
  LOG: file
script:
  - tools/pre_deploy
deploy:
  bash:
    script:
      - ssh deploy@46.101.34.92 'rm -rf app-build'
      - scp -o StrictHostKeyChecking=no -P 22 -r . deploy@46.101.34.92:app-build/
      - ssh deploy@46.101.34.92 app-build/tools/deploy
    when:
      branch: release
notify:
  email:
    recipients:
      - build@mikefarrow.co.uk