storage:
  extends:
    file: docker-compose-common.yml
    service: storage

data:
  extends:
    file: docker-compose-common.yml
    service: data

db:
  extends:
    file: docker-compose-common.yml
    service: db
  restart: always

fpm:
  extends:
    file: docker-compose-common.yml
    service: fpm
  links:
    - db
  volumes_from:
    - storage
    - data
  restart: always

nginx:
  extends:
    file: docker-compose-common.yml
    service: nginx
  links:
    - fpm
    - db
  volumes_from:
    - storage
    - data
  restart: always

