db:
  extends:
    file: docker-common.yml
    service: db
composer:
  image: composer/composer
  volumes:
    - .:/app
buildtools:
  build: docker/build/buildtools
  volumes:
    - .:/data
wpcli:
  build: docker/build/wpcli
  volumes:
    - .:/var/www
    - public:/var/www/html
  links:
    - db