storage:
  extends:
    file: docker-compose-common.yml
    service: storage

data:
  extends:
    file: docker-compose-common.yml
    service: data

db:
  extends:
    file: docker-compose-common.yml
    service: db
  volumes_from:
    - storage

composer:
  image: weyforth/wordpress-composer
  volumes_from:
    - storage
    - data

wpcli:
  image: weyforth/wordpress-wpcli
  volumes_from:
    - storage
    - data
  links:
    - db

buildtools:
  image: weyforth/wordpress-buildtools
  volumes_from:
    - storage
    - data
