#!/bin/bash

set -e

build_env="local"

if [[ "$1" != "" ]];
	then
	build_env="$1"
fi

cp "www/.env.$build_env" www/.env.example

tools/build_link

tools/composer install
tools/npm install
tools/bower install

tools/gulp
