#!/bin/bash

set -e

tools/npm link gulp
tools/npm link gulp-copy
tools/npm link gulp-bower
tools/npm link gulp-minify-css
tools/npm link gulp-uglify
tools/npm link gulp-compass
tools/npm link gulp-requirejs-optimize
tools/npm link gulp-modulizr
