#!/bin/bash

set -e

build_env="local"

if [[ "$1" != "" ]];
	then
	build_env="$1"
fi

composer_args=""
bower_args=""
npm_args=""

if [[ "$install_env" != "local" ]]; then
	composer_args="--quiet"
	bower_args="--quiet"
	npm_args="--silent"
fi

cp "www/.env.$build_env" www/.env.example

echo ""
echo "Linking npm tools"
tools/build_link

echo ""
echo "Installing Composer dependencies"
tools/composer install $composer_args

echo ""
echo "Installing NPM dependencies"
tools/npm install $npm_args

echo ""
echo "Installing Bower dependencies"
tools/bower install $bower_args

echo ""
echo "Gulping"
tools/gulp
