#!/bin/bash

i=0
timeout=30
host="db"
port=3306

echo -n "Waiting for mysql connection to $host:$port..."

while ! nc -w 1 $host $port 2>/dev/null 1>/dev/null
do
  ((i++))
  echo -n .
  sleep 1
  if [[ $i == $timeout ]];
    then
    echo "timed out"
    exit 1
  fi
done

echo " done"
exit 0
