#!/bin/bash

source app-build/tools/_functions

set -e

if [[ -d app ]]; then

	cd app

	docker-compose run --rm data rm -rf /data/www
	tools/stop production

	cd ../

fi

heading "Copying files"

rm -rf app && cp -r app-build app && echo "done"

cd app

tools/start production
tools/install production

echo ""

# mkdir -p app-shared
# mkdir -p app-shared/logs

# rm -rf app/logs/
# ln -s app-shared/logs/ app/logs
