#!/bin/bash

set -e

cd app-build

tools/stop production

cd ../

rm -rf app
cp -r app-build app

cd app

tools/start production
tools/install

# mkdir -p app-shared
# mkdir -p app-shared/logs

# rm -rf app/logs/
# ln -s app-shared/logs/ app/logs
