#!/bin/bash

set -e

exec docker-compose pull
exec docker-compose -f docker-compose-tools.yml pull

tools/build "$@"

exec docker-compose -f docker-compose-tools.yml run --rm wpcli ../tools/dbisup

tools/wp core install --url=http://dummy --title="Wordpress-Framework" --admin_user=admin --admin_password=adminpass --admin_email=contact@mikefarrow.co.uk
tools/wp rewrite structure '/%postname%'
tools/wp plugin activate --all
tools/wp theme activate roots
