#!/bin/bash

source tools/_functions

set -e

install_env="local"

if [[ "$1" != "" ]];
	then
	install_env="$1"
fi

[ -t 1 ] || params="-T"

if [[ "$build_env" != "local" ]]; then
	heading "Pulling Docker images"
	docker-compose -f docker-compose-tools.yml pull >/dev/null
fi

heading "Database"
docker-compose -f docker-compose-tools.yml run $params --rm wpcli ../tools/dbisup

heading "Installing"

if ! $(tools/wp core is-installed); then

	tools/wp core install --url=http://dummy --title="Wordpress-Framework" --admin_user=admin --admin_password=adminpass --admin_email=contact@mikefarrow.co.uk
	tools/wp rewrite structure '/%postname%'
	tools/wp plugin activate --all

	if [[ "$install_env" == "local" ]]; then
		tools/wp plugin deactivate w3-total-cache
	fi

	tools/wp theme activate roots

else

	echo "Already Installed"

fi
