#!/bin/bash

source tools/_functions

build_env=""

if [[ "$1" != "" ]];
	then
	build_env="-$1"
fi

if [[ "$build_env" != "local" ]]; then
	heading "Pulling Docker images"
	docker-compose -f "docker-compose$build_env.yml" pull >/dev/null
fi

heading "Starting"

if [[ $(docker-compose ps | grep _nginx) ]]; then

	docker-compose -f "docker-compose$build_env.yml" up --no-recreate -d db fpm nginx

else

	docker-compose -f "docker-compose$build_env.yml" up -d

fi
