#!/bin/bash

build_env=""

if [[ "$1" != "" ]];
	then
	build_env="-$1"
fi

if [[ $(docker ps | grep _nginx | grep Up) ]]; then

	docker-compose -f "docker-compose$build_env.yml" build nginx
	docker-compose -f "docker-compose$build_env.yml" up --no-deps -d nginx

else

	docker-compose -f "docker-compose$build_env.yml" up -d

fi
