#!/bin/bash

build_env=""

if [[ "$1" != "" ]];
	then
	build_env="-$1"
fi

if [[ $(docker ps | grep Up) ]]; then

	docker-compose -f "docker-compose$build_env.yml" stop nginx
	docker-compose -f "docker-compose$build_env.yml" rm -fv data

fi
